# Çoklu Doğrusal Regresyon¶


In [1]:
import pandas as pd
ad = pd.read_csv("Advertising.csv", usecols = [1,2,3,4])
df = ad.copy()
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [2]:
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
import statsmodels.api as sm

In [3]:
X = df.drop("sales", axis = 1)
y = df["sales"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state= 42)


In [4]:
X_train.shape,y_train.shape

((160, 3), (160,))

In [5]:
X_test.shape

(40, 3)

In [6]:
training = df.copy()

In [7]:
training.shape

(200, 4)

## 1-)Statsmodels yontemi ile model

* *Regresyon modelini eger daha cok yorumlama beklentimiz varsa statmodels kullanilir, daha genel yontem scikitlearn*

In [8]:
lm = sm.OLS(y_train, X_train)

In [9]:
model = lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.982
Method:                 Least Squares   F-statistic:                     2935.
Date:                Mon, 01 Mar 2021   Prob (F-statistic):          1.28e-137
Time:                        16:06:12   Log-Likelihood:                -336.65
No. Observations:                 160   AIC:                             679.3
Df Residuals:                     157   BIC:                             688.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0531      0.001     36.467      0.000       0.050       0.056
radio          0.2188      0.011     20.138      0.000       0.197       0.240
newspaper      0.0239      0.008      3.011      0.003       0.008       0.040
==============================================================================
Omnibus:                       11.405   Durbin-Watson:                   1.895
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               15.574
Skew:                          -0.432   Prob(JB):                     0.000415
Kurtosis:                       4.261   Cond. No.                         13.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

* *Yukaridaki tablodan modele dahil ettigimiz butun degiskenlerin anlamli oldugunu saptadik*

In [10]:
model.summary().tables[1]
# katsayilar ve olmasi gereken araliklar

<class 'statsmodels.iolib.table.SimpleTable'>

## 2-)Scikit learn yontemi ile model

In [11]:
from sklearn.linear_model import LinearRegression


In [12]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [13]:
model.intercept_
#sabit katsayi

2.979067338122629

In [14]:
model.coef_
# diger degiskenlerin katsayilari

array([0.04472952, 0.18919505, 0.00276111])

In [16]:
model.predict(X)

array([20.61397147, 12.52942275, 12.62381325, 17.73087016, 13.27071976,
       12.82693587, 11.82149856, 12.09580733,  3.76381192, 12.46646769,
        7.09983872, 17.1342205 , 10.86633369,  8.79795773, 18.4598904 ,
       20.88988209, 13.25103464, 23.21214788, 10.00337695, 14.14222434,
       18.13614046, 14.62763575,  6.7146496 , 16.46055379,  8.20010235,
       15.4544819 , 14.94912051, 16.94141141, 19.29818677,  9.2767456 ,
       21.55384318, 11.42760282,  7.69340245, 18.6439566 ,  7.54498748,
       16.78110726, 23.2179245 , 15.7927809 , 10.0553326 , 20.39840652,
       16.34309555, 17.32216187, 21.35732668, 13.89573638,  9.08364737,
       15.15506967,  8.96290787, 21.61235394, 16.26867517,  8.2866632 ,
       12.59806415,  9.29612342, 20.65730881, 20.04956615, 20.22223086,
       21.3876709 ,  8.73628397, 12.74960716, 21.89621832, 18.01050913,
        5.80957448, 22.89655202, 16.69074263, 13.19615575, 17.0204516 ,
        7.82740305,  9.04831992, 11.98138077, 18.83109103, 21.05

### Tahmin asamasi<br>
model denklemi <br>
sales = 2.97 + TV * 0.04 + Radio * 0.18 + newspaper * 0.002 <br> 
soru : 40 birim TV, 10 birim Radio, 20 birim newspaper harcamasi sales üzerinde etkisi?

In [17]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

In [18]:
data = [[40],[10],[20]]
data = pd.DataFrame(data).T
# T islemi predict fonksiyonunn matris boyutuna uygun olmasi icin yapilir

In [19]:
model.predict(data)

array([6.71542087])

In [20]:
rmse = np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

In [21]:
rmse
# egitim hatasi

1.644727765644337

In [22]:
rmse = np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

In [23]:
rmse
# test seti hatasi

1.7815996615334502

### Model Tuning / Model Dogrulama

In [36]:
X = df.drop("sales", axis = 1)
y = df["sales"]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.20, 
                                                    random_state= 144)
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [37]:
np.sqrt(mean_squared_error(y_train , model.predict(X_train)))

1.6748559274650712

In [38]:
model.score(X_train, y_train)
           

0.8971614078663419

* *Random state degistikce test hatasi ve score degisir.En uygun degeri bulmak icin cross validation yontemini kullaniriz*

In [39]:
cross_val_score(model, X_train, y_train, cv = 10, scoring = "r2").mean()
# ilk param model, 2. bagimsiz degiskenler, 3. bagimli degiskenler, 
# 4. param cross validation islemi yapilma sayisi

0.8733783298422942

* *model score ve cross_val_score farkini goruruz*

In [44]:
np.sqrt(-cross_val_score(model, X_train, y_train, cv = 10, 
                scoring = "neg_mean_squared_error").mean())

1.7461905497850763

* *Valide edilmis degerler bize daha gercekci bilgi saglar*

In [45]:
np.sqrt(-cross_val_score(model, 
                X_test, 
                y_test, 
                cv = 10, 
                scoring = "neg_mean_squared_error")).mean()

1.7399924960346644

In [46]:
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.6640263686701033

* *Ayni kiyaslamalar test seti uzerinden de yapilmali*