# Neden Numpy?

In [1]:
a=[2,5,4,1]
b=[5,2,3,4]


In [2]:
ab=[]
for i in range (0,len(a)):
    ab.append(a[i]*b[i])
ab

[10, 10, 12, 4]

In [3]:
import numpy as np


In [4]:
a=np.array([2,5,4,1])
b=np.array([5,2,3,4])
a*b


array([10, 10, 12,  4])

* *numpy daha ileri seviye islemleri(cok boyutlu matris carpimi gibi) isleri daha kolay yapmamızı saglar*
* *Ayni zamanda numpy optimizasyon konusunda daha verimlidir.*

## Numpy array olusturma

In [5]:
import numpy as np

In [6]:
a=np.array([2,6,82,35])
type(a)

numpy.ndarray

In [7]:
b=np.array([3.14,23,5,2])
b

array([ 3.14, 23.  ,  5.  ,  2.  ])

* *numpy hafiza kismindaki optimizasyonunu liste icinde "tek tip" eleman tutmaya borclu.Bu yüzden farkli tipte elemanlar girilirse onlari tek tipe indirger.*

In [8]:
b=np.array([3.14,23,5,2],dtype=int) # farkli tipteki elemanlarin hangi tipe indirgenecegi belirtilir
b

array([ 3, 23,  5,  2])

In [9]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
#multidimensional array

In [11]:
np.full((3,6),5) # verilen boyutta verilen elemanlardan olusan matris

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [12]:
np.arange(1,10)# verilen sayılar arası dizi olusturma

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,23,4)

array([ 0,  4,  8, 12, 16, 20])

In [14]:
np.linspace(0,1,10) # dogrusal dizi olusturma, 2 deger arasinda 10 tane deger olusturdu

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(8,4,(3,5))
# ilk parametre ortalama,ikinci parametre s.sapma,ucuncu parametre boyut bilgisi
# dagilimini bizim belirledigimiz random sayilardan olusan matris

array([[10.0235296 ,  9.39204456,  5.22487055,  7.42623895,  7.18394703],
       [ 4.69430526, -3.22745112, 11.53352275,  9.06138027, 10.53549788],
       [ 9.88162147, 14.6708179 ,  8.42903613,  4.01221529,  6.93511246]])

In [16]:
np.random.randint(12) # rastegele int olusturma

5

## Numpy Array Ozellikleri

* **ndim** : boyut sayisi
* **shape** : boyut bilgisi
* **size** : toplam eleman sayisi
* **dtype** : veri tipi

In [17]:
import numpy as np

In [18]:
a=np.random.randint(12,size=(3,6))

In [19]:
a

array([[ 1,  9, 11,  6,  7,  2],
       [ 5,  3, 10,  9,  1,  1],
       [10,  4, 10,  3,  8,  1]])

In [20]:
a.ndim

2

In [21]:
a.shape

(3, 6)

In [22]:
a.size

18

In [23]:
a.dtype

dtype('int32')

## Yeniden sekillendirme(reshape)

In [24]:
import numpy as np

In [25]:
a=np.arange(1,10)

In [26]:
a.reshape(3,3)
# reshape kendisine verilen diziyi, girilen parametre boyutundaki diziye şekillendirir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a.reshape(1,3)
# bu reshape hata verir cünkü bilgi kaybı olması soz konusu degil,ona gore parametre girilmeli

ValueError: cannot reshape array of size 9 into shape (1,3)

## Array birlestirme(concatenation)

In [28]:
import numpy as np

In [29]:
x=np.array([2,5,6])
y=np.array([4,1,7])

In [30]:
np.concatenate([x,y])

array([2, 5, 6, 4, 1, 7])

In [31]:
z=np.array([3,6,2])

In [32]:
np.concatenate([x,y,z])

array([2, 5, 6, 4, 1, 7, 3, 6, 2])

In [33]:
x=np.array([[3,5,6],
            [3,765,7]])

In [34]:
np.concatenate([x,x])
# multidimensional array concatenation(default row)

array([[  3,   5,   6],
       [  3, 765,   7],
       [  3,   5,   6],
       [  3, 765,   7]])

In [35]:
np.concatenate([x,x],axis=1)
# axis argumani neye gore birlestirilecegini sorar, 0-row, 1-column baz alınarak yerlestirir

array([[  3,   5,   6,   3,   5,   6],
       [  3, 765,   7,   3, 765,   7]])

## Array ayirma(splitting)

In [36]:
import numpy as np

In [37]:
x=np.array([1,35,7,36,82,34,6,2])

In [38]:
np.split(x,[3,6])
# verilen ilk indise kadar bir array split eder,
# daha sonra 2. indise kadar bi array split eder,en son geriye kalan arrayi de dondurur.

[array([ 1, 35,  7]), array([36, 82, 34]), array([6, 2])]

In [39]:
a,b,c=np.split(x,[3,6])
# bolunen listeleri hafızada tutmus oluruz

In [40]:
x=np.arange(9).reshape([3,3])
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.vsplit(x,[2])
# cok boyutlu dizi bolme

[array([[0, 1, 2],
        [3, 4, 5]]), array([[6, 7, 8]])]

## Array sıralama(sorting)

In [42]:
import numpy as np

In [43]:
x=np.array([34,52,6,83,4])

In [44]:
np.sort(x)
# bu metod x uzerinde kalici degisiklik yapmaz, 
# siralanmis hali baska degiskene atilarak tutulabilir

array([ 4,  6, 34, 52, 83])

In [45]:
x.sort()# bu metod ise x degiskenini tamamen degistirir
x


array([ 4,  6, 34, 52, 83])

In [46]:
y=np.random.normal(3,5,[3,4])
y

array([[ 3.03775737,  7.49802908, -9.73384432,  3.65038495],
       [ 0.70285128, -3.07509148, -1.35746757,  5.41008089],
       [ 7.69051126,  2.30407549,  5.5961755 ,  2.84633031]])

In [47]:
np.sort(y)
# default olarak row bazli siralama yapilir

array([[-9.73384432,  3.03775737,  3.65038495,  7.49802908],
       [-3.07509148, -1.35746757,  0.70285128,  5.41008089],
       [ 2.30407549,  2.84633031,  5.5961755 ,  7.69051126]])

In [48]:
np.sort(y,axis=0) # column bazli siralama

array([[ 0.70285128, -3.07509148, -9.73384432,  2.84633031],
       [ 3.03775737,  2.30407549, -1.35746757,  3.65038495],
       [ 7.69051126,  7.49802908,  5.5961755 ,  5.41008089]])

### Array alt kumesine erisim(Slice) 

In [49]:
import numpy as np

In [50]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a[0:3]

array([1, 2, 3])

In [52]:
a[:3]

array([1, 2, 3])

In [53]:
a[3:]

array([4, 5, 6, 7, 8, 9])

In [54]:
a[1::2] # ilk indisten son indise kadar 2şer olarak ilerler

array([2, 4, 6, 8])

In [55]:
m=np.random.randint(10,size=(5,5))
m

array([[4, 6, 7, 1, 4],
       [0, 2, 9, 9, 8],
       [4, 3, 6, 3, 0],
       [4, 3, 8, 3, 9],
       [0, 6, 4, 2, 4]])

In [56]:
m[:,0] # virgulden oncesi satir islemlerini, sonrasi sutun islemlerini kapsar

array([4, 0, 4, 4, 0])

In [57]:
m[0,:]

array([4, 6, 7, 1, 4])

In [58]:
m[:,:2]

array([[4, 6],
       [0, 2],
       [4, 3],
       [4, 3],
       [0, 6]])

### Alt kume uzerinde islem yapma

In [59]:
import numpy as np 

In [60]:
a=np.random.randint(10,size=(5,5))
a

array([[2, 7, 4, 8, 5],
       [0, 6, 3, 3, 1],
       [7, 0, 7, 4, 5],
       [0, 1, 0, 9, 9],
       [1, 2, 1, 5, 0]])

In [61]:
altKume=a[0:3,0:2]
altKume

array([[2, 7],
       [0, 6],
       [7, 0]])

In [62]:
altKume[0,0]=98989
altKume

array([[98989,     7],
       [    0,     6],
       [    7,     0]])

In [63]:
a # Altkumede yapilan degisiklik ana arraye de yansidi...

array([[98989,     7,     4,     8,     5],
       [    0,     6,     3,     3,     1],
       [    7,     0,     7,     4,     5],
       [    0,     1,     0,     9,     9],
       [    1,     2,     1,     5,     0]])

In [64]:
x=np.random.randint(10,size=(5,5))
x

array([[8, 7, 1, 6, 5],
       [9, 5, 9, 4, 1],
       [5, 4, 7, 7, 1],
       [4, 5, 7, 5, 6],
       [3, 9, 5, 9, 3]])

In [65]:
alt_b=x[0:3,0:2].copy()

In [66]:
alt_b[0][0] = 99999
alt_b

array([[99999,     7],
       [    9,     5],
       [    5,     4]])

In [67]:
x # alt kumede yapilan degisiklikler copy metodu sayesinde ana kumeye yansimadi

array([[8, 7, 1, 6, 5],
       [9, 5, 9, 4, 1],
       [5, 4, 7, 7, 1],
       [4, 5, 7, 5, 6],
       [3, 9, 5, 9, 3]])

### Fancy ındex ile elemanlara erisme

In [68]:
import numpy as np

In [69]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [70]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [71]:
alGetir = [1,3,5]

In [72]:
v[alGetir] # fancy index yontemi 

array([ 3,  9, 15])

In [73]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
satir = np.array([1,0])
sutun = np.array([1,1])

In [75]:
m[satir,sutun]

array([4, 1])

### Kosullu eleman islemleri

In [76]:
import numpy as np

In [77]:
v = np.array([1,2,3,4,5])

In [78]:
v > 3

array([False, False, False,  True,  True])

In [79]:
v[v > 3] , v[v != 3] # icerideki sarti saglayan degiskenleri verir fancy ile

(array([4, 5]), array([1, 2, 4, 5]))

In [80]:
v + 1
#matematiksel islemler arka planda numpydan spesifik fonksiyonlar cagırlarak yapılır. UFUNC

array([2, 3, 4, 5, 6])

In [81]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\90530\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\90530\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

### Numpy ile iki bilinmeyenli denkem cozme

problem
* **5* x0 + 3* x1 = 12**
* **4* x0 + 3* x3 = 43**

In [82]:
import numpy as np

In [83]:
a = np.array([[5,3],[4,3]]) # kaysayilar matrisi
b = np .array([12,43])    #sonuc matrisi

In [84]:
a

array([[5, 3],
       [4, 3]])

In [85]:
b

array([12, 43])

In [86]:
x = np.linalg.solve(a,b)
x

array([-31.        ,  55.66666667])